@startuml
'skinparam linetype polyline
'skinparam linetype ortho
hide circle
hide stereotype

'!pragma layout smetana

skinparam class<<MD>> {
 BorderColor DarkSlateGray
 BackgroundColor WhiteSmoke
 HeaderBackgroundColor #909090
}

skinparam class<<TM>> {
 BorderColor #505090
 BackgroundColor APPLICATION
 HeaderBackgroundColor SkyBlue
}


    class "**Receipt Notice**"<<MD>> {
        |_ identifier 0..*
        |_ status 1..1
        |_ dateTime 0..1
        |_ shipmentIdentifier 0..1
        |_ requestIdentifier 0..1
        |_ supplier 0..1
        |_ supplierLocation 0..1
        |_ receiver 0..1
        |_ receiverLocation 0..1
        |_ item 1..*
          |_ item 1..1
          |_ itemCharacteristics 0..*
          |_ quantity 1..1
          |_ origin 0..1
        |_ additionalInfo 0..*  
          |_ reference 0..*  
          |_ notes 0..*  
        --
    }


@enduml