@startuml

hide footbox

'!include ./style.iuml


Participant "[[actors_and_transactions.html#supply-requester Supply\nRequester]]" as SR
Participant "[[actors_and_transactions.html#supply-request-filler Supply\nRequest Filler]]" as RF

activate SR
activate RF

SR -[hidden]> RF 
SR --> RF: \t(Request status) 
SR <-- RF: \t\n\t \n\t [[StructureDefinition-SupplyRequest.html{Supply Request Status} ~[Supply Request Status]]]
SR -[hidden]> RF

deactivate SR
deactivate RF

@enduml
