@startuml

hide footbox

'!include ./style.iuml


Participant "[[actors_and_transactions.html#supply-requester Supply\nRequester]]" as SR
Participant "[[actors_and_transactions.html#supply-request-filler Supply\nRequest Filler]]" as RF

activate SR
activate RF

SR -[hidden]> RF 
SR -> RF: \tRequest supply \n\t [[PHARM-S1.html{Supply Request Status} ]]
SR <-- RF: \t(response)\n\t [[PHARM-S1.html{Supply Request Status} ~[StructureDefinition-ihe-supply-request.html~]]]
SR -[hidden]> RF

deactivate SR
deactivate RF

@enduml
