@startuml

hide footbox

'!include ./style.iuml


Participant "[[actors_and_transactions.html#supplier Supplier]]" as S
Participant "[[actors_and_transactions.html#receiver Receiver]]" as R

activate S
activate R

S -[hidden]> R
S -> R: \tInform Reception \n\t [[StructureDefinition-ihe-supply-delivery-receipt.html{Receipt Notice} ~[Receipt Notice~]]]
S <-- R: \t(response)\t
S -[hidden]> R

deactivate S
deactivate R

@enduml
