@startuml

hide footbox

'!include ./style.iuml


participant "[[actors_and_transactions.html#inventory-reporter Inventory\nReporter]]" as IR
participant "[[actors_and_transactions.html#inventory-manager Inventory\nManager]]" as IM

activate IR
activate IM

IR -[hidden]> IM
IR -> IM: Report Inventory Status\n[[PHARM-S6.html{Inventory Status report} ~[PHARM-S6~]]]
IR <-- IM: \t(response)\t
IR -[hidden]> IM :"  "

deactivate IR
deactivate IM

@enduml
