@startuml

hide footbox

'!include ./style.iuml


Participant "[[actors_and_transactions.html#inventory-reporter Inventory\nReporter]]" as IR
Participant "[[actors_and_transactions.html#inventory-manager Inventory\nManager]]" as IM

activate IR
activate IM

IR -[hidden]> IM
IR <- IM: Query Inventory Status \n[[PHARM-S5.html {Inventory Query} ~[PHARM-S5~]]]
IR --> IM: \t(response)\t
IR -[hidden]> IM :"  "

deactivate IR
deactivate IM

@enduml
