@startuml

hide footbox

!include ./style.iuml


Participant "[[actor_definitions.html#inventory-report Inventory\nReporter]]" as IR
Participant "[[actor_definitions.html#inventory-manager Inventory\nManager]]" as IM

activate IR
activate IM

IR -> IM: \tReport Inventory Consumption [[PHARM-S6.html{Consumption report}  ~[PHARM-S6~]]]
IR <-- IM: \t(response)\t

deactivate IR
deactivate IM

@enduml
