@startuml

hide footbox

'!include ./style.iuml


Participant "[[actors_and_transactions.html#inventory-reporter Inventory\nReporter]]" as IR
Participant "[[actors_and_transactions.html#inventory-manager Inventory\nManager]]" as IM

activate IR
activate IM
IR -[hidden]> IM
IR -> IM: Inventory Query\n[[PHARM-S7.html{Inventory query}  ~[StructureDefinition-ihe-supply-inventory-query.html~]]]
IR <-- IM: \t(response)\t
IR -[hidden]> IM :"  "

deactivate IR
deactivate IM

@enduml
