@startuml

hide footbox

'!include ./style.iuml


Participant "[[actors_and_transactions.html#inventory-reporter Inventory\nReporter]]" as IR
Participant "[[actors_and_transactions.html#inventory-manager Inventory\nManager]]" as IM

activate IR
activate IM
IR -[hidden]> IM
IR -> IM: Report Inventory Consumption\n[[PHARM-S7.html{Consumption notice} ~[PHARM-S7~]]]
IR <-- IM: \t(response)\t
IR -[hidden]> IM :"  "

deactivate IR
deactivate IM

@enduml
