@startuml

hide footbox

'!include ./style.iuml


Participant "[[actors_and_transactions.html#supplier Supplier]]" as S
Participant "[[actors_and_transactions.html#receiver Receiver]]" as R

activate S
activate R

S -[hidden]> R
S -> R: \t[[StructureDefinition-DispatchNotice.html{Dispatch Notice} ~[Dispatch notice~]]]
S <-- R: \t(response)\t
S -[hidden]> R

deactivate S
deactivate R

@enduml
