@startuml

hide footbox

!include ./style.iuml


Participant "Supply\nRequester" as SR
Participant "Supply\nRequest Filler" as RF

activate SR
activate RF

SR -> RF: \tRequest resupply \t [[StructureDefinition-ihe-supply-order.html{Profile}  ~[S1~]]]
SR <-- RF: \t(http response)\t

deactivate SR
deactivate RF

@enduml
