@startuml
!include style.iuml

title Check Dispensed product according to Falsified Medicines Directive
hide footbox

actor Physician
actor "Dispensing\nPharmacist " as DP
Participant "Pharmacy\nDispensing\nSystem" as PDS
Participant "FMD Verifier" as HUB

'group Picking
'end
'group Tracking
'end

'activate PDS
DP -> DP: Retrieve first item\nfrom inventory
group Check First item
DP -> PDS: Scan barcode of first item
activate PDS
PDS -> HUB: Query product status
deactivate PDS
activate HUB
HUB -> PDS: Response: "Product Not OK"
deactivate HUB
activate PDS
PDS -> DP: Display error
deactivate PDS
end

DP -> DP: Retrieve second item\nfrom inventory
group Check Second item
DP -> PDS: Scan barcode of first item
activate PDS
PDS -> HUB: Query product status
deactivate PDS
activate HUB
HUB -> PDS: Response: "Product OK"
deactivate HUB
activate PDS
PDS -> DP: Display message
deactivate PDS
end



group Dispense
DP -> DP: Deliver medication to patient
DP -> PDS: Confirm dispense
activate PDS
PDS -> PDS: Update inventory\n(two items consumed)
end


@enduml
